### ISSUE TITLE
Wont open specific save games

### ISSUE THREAD

**Issue by pandaonea** [midspace/SEToolbox#175] opened 2019-06-14 23:55 UTC
[X ] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [ X] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [ X] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

SEToolbox Version: 1.191.20.1
SE Version: 1.191.023

SEToolbox crashed

What were you doing with SEToolbox when it happened?
Trying to load a save game file to edit it.

Steps to Reproduce
1) SEToolbox opened normally. 
2) Tried to open file.
3) Editor crashed. World before Space engineers update, and SEtoolbox update opened normally.
4) Tried to open older version of same save game, editor crashed. Before version update for space engineers.
5) Was able to open another world in editor.How did this issue get triggered?
Game based on Template from Steam's Workshop, with name "Empty World"

```
2019-06-14 16:06:16,528 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" /B /B
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin64
SEBinVersion: 1.191.23
ProcessorCount: 6
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: 
Times started total: 22
Times started since last reset: 22
Times started since game update: 15

Files:
2019-06-07T21:15:31.0494331-07:00	252,600	0.1.1	HavokWrapper.dll
2017-06-02T07:49:12.0000000-07:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
2017-03-08T17:26:22.0000000-08:00	276,480	2.0.8.0	log4net.dll
2018-07-08T06:26:21.5461292-07:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2018-07-08T06:26:21.5461292-07:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2019-06-06T23:15:14.9385580-07:00	98,616	4.6.26011.1	netstandard.dll
2018-09-09T00:31:30.0000000-07:00	911,360	0.32.0.0	Octokit.dll
2019-06-07T21:15:30.7336800-07:00	281,784	2.4.0.8641	protobuf-net.dll
2019-06-07T21:15:31.4759730-07:00	73,400	1.0.0.0	Sandbox.Common.dll
2019-06-07T21:15:30.7366799-07:00	7,455,928	0.1.1	Sandbox.Game.dll
2019-06-07T21:15:31.4829725-07:00	94,904	0.1.1.0	Sandbox.Game.XmlSerializers.dll
2019-06-07T21:15:30.7376795-07:00	383,160	0.1.1	Sandbox.Graphics.dll
2019-06-07T21:15:31.4839718-07:00	20,152	1.0.0.0	Sandbox.RenderDirect.dll
2019-06-07T07:10:24.0000000-07:00	1,327,104	01.191.20.1	SEToolbox.exe
2017-06-02T07:49:12.0000000-07:00	745		SEToolbox.exe.config
2019-06-07T06:54:38.0000000-07:00	62,464	1.0.0.0	SEToolbox.ImageLibrary.dll
2019-06-07T07:10:20.0000000-07:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2019-06-07T07:10:24.0000000-07:00	2,262,528		SEToolbox.pdb
2019-06-07T07:10:20.0000000-07:00	53,760	1.0.0.0	SEToolboxUpdate.exe
2019-06-07T21:15:30.7386797-07:00	501,944	4.2.0	SharpDX.Direct2D1.dll
2019-06-07T21:15:30.7396796-07:00	289,464	4.2.0	SharpDX.Direct3D11.dll
2019-06-07T21:15:30.7406798-07:00	281,272	4.2.0	SharpDX.dll
2019-06-07T21:15:31.5096846-07:00	154,808	4.2.0	SharpDX.DXGI.dll
2019-06-07T21:15:30.7446796-07:00	488,120	1.0.0.0	SpaceEngineers.Game.dll
2019-06-07T21:15:31.5342912-07:00	61,624	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2019-06-07T21:15:30.7456795-07:00	5,079,224	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2019-06-07T21:15:30.7466794-07:00	327,864	11.0.0	Steamworks.NET.dll
2018-07-19T18:26:18.1672842-07:00	250,656	04.28.51.07	steam_api64.dll
2019-06-07T21:15:30.7476796-07:00	322,232	1.0.102.0	System.Data.SQLite.dll
2013-03-09T16:25:10.0000000-08:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
2019-06-07T21:15:31.7453314-07:00	23,224	1.0.0.0	VRage.Ansel.dll
2019-06-07T21:15:31.7473338-07:00	65,208	1.0.0.0	VRage.Audio.dll
2019-06-07T21:15:30.7496793-07:00	486,072	1.0.0.0	VRage.dll
2019-06-07T21:15:30.7506792-07:00	1,359,032	1.0.0.0	VRage.Game.dll
2019-06-07T21:15:30.7516797-07:00	7,031,992	1.0.0.0	VRage.Game.XmlSerializers.dll
2019-06-07T21:15:31.7573330-07:00	48,824	1.0.0.0	VRage.Input.dll
2019-06-07T21:15:30.7526793-07:00	406,200	1.0.0.0	VRage.Library.dll
2019-06-07T21:15:30.7536798-07:00	543,928	1.0.0.0	VRage.Math.dll
2019-06-07T21:15:31.7623310-07:00	101,048		VRage.Native.dll
2019-06-07T21:15:31.7673307-07:00	23,224	0.1.1	VRage.NativeWrapper.dll
2019-06-07T21:15:30.7556795-07:00	342,200	1.0.0.0	VRage.Render.dll
2019-06-07T21:15:30.7566794-07:00	920,248	1.0.0.0	VRage.Render11.dll
2018-03-27T14:51:20.0000000-07:00	77,824	3.0.1.0	WPFLocalizeExtension.dll
2018-01-08T19:35:48.0000000-08:00	27,648	1.2.2	XAMLMarkupExtensions.dll

System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Sandbox.Game.World.Generator.MyCompositeShapes.CombinedGenerator(Int32 version, Int32 seed, Single size)
   at Sandbox.Game.World.Generator.MyCompositeShapes.<>c__DisplayClass4_0.<.cctor>b__3(Int32 generatorSeed, Int32 seed, Single size)
   at Sandbox.Game.World.Generator.MyCompositeShapeProvider.InitFromState(State state)
   at Sandbox.Game.World.Generator.MyCompositeShapeProvider.VRage.Voxels.IMyStorageDataProvider.ReadFrom(Int32 storageVersion, Stream stream, Int32 size, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyOctreeStorage.ReadDataProvider(Stream stream, ChunkHeader header, Boolean& isOldFormat, IMyStorageDataProvider& provider)
   at Sandbox.Engine.Voxels.MyOctreeStorage.LoadInternal(Int32 fileVersion, Stream stream, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyStorageBase.Load(Stream stream, MyStorageBase& storage, Boolean& isOldFormat)
   at Sandbox.Engine.Voxels.MyStorageBase.Load(Byte[] memoryBuffer)
   at Sandbox.Engine.Voxels.MyStorageBase.LoadFromFile(String absoluteFilePath, Dictionary`2 modifiers, Boolean cache)
   at SEToolbox.Interop.Asteroids.MyVoxelMap.Load(String filename) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Interop\Asteroids\MyVoxelMap.cs:line 202
   at SEToolbox.Models.StructureVoxelModel.ReadVoxelDetails(String filename) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureVoxelModel.cs:line 359
   at SEToolbox.Models.StructureVoxelModel..ctor(MyObjectBuilder_EntityBase entityBase, String voxelPath) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureVoxelModel.cs:line 78
   at SEToolbox.Models.StructureBaseModel.Create(MyObjectBuilder_EntityBase entityBase, String savefilePath) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\StructureBaseModel.cs:line 390
   at SEToolbox.Models.ExplorerModel.LoadSectorDetail() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\ExplorerModel.cs:line 456
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


```
![Error](https://user-images.githubusercontent.com/51839967/59544017-94ef7a00-8ec3-11e9-935d-8abf028013bb.png)
![Select](https://user-images.githubusercontent.com/51839967/59544020-a0db3c00-8ec3-11e9-8971-cb9093549aff.png)
[save game.zip](https://github.com/midspace/SEToolbox/files/3292520/save.game.zip)

The save game file did not include one of the asteroids that was over 100MB is file size.  I moved the file somewhere else to see if that was the problem for the memory error and still got the same message.

**Comment by etmoonshade** [comment] 2019-06-16 18:05
I'm going to +1 this - I'm having the exact same issue (with a different world file, of course)

**Comment by midspace** [comment] 2019-06-17 08:48
Duplicate of #174, but this gave better detail to track it down.

Looks like there are more game dependencies than ever.
There are two new ones to be copied across from the game folder.
`System.Memory.dll` and `System.Runtime.CompilerServices.Unsafe.dll`
A temporary fix is to copy these across manually.
I'll be releasing a fix for this later this week, or sooner if I can fix another bug from the last release.

**Comment by midspace** [comment] 2019-06-18 08:16
Please download the [latest release](https://github.com/midspace/SEToolbox/releases/latest) for a fix to this issue.

**Closed** 2019-06-20 21:05 UTC
Labels: bug
