### ISSUE TITLE
Mirror 2x1x1 blocks

### ISSUE THREAD

**Issue by omen964** [midspace/SEToolbox#132] opened 2018-03-23 15:01 UTC
So i have notice that this bug is still in the toolbox

The 2x1x1 blocks and the half block and half corner block dose not translate to correct rotation or don't even spawn when you try to use the mirror option on the grid that has them.

**Comment by midspace** [comment] 2018-03-24 00:09
Duplicate of #10

**Closed by midspace** 2018-03-24 00:09 UTC
